services:
    zookeeper:
        image: ghcr.io/arm64-compat/confluentinc/cp-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
    kafka:
        image: ghcr.io/arm64-compat/confluentinc/cp-kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
            - "29092:29092"
          environment:
              KAFKA_BROKER_ID: 1
              KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
              KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
              KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
              KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    schema-registry:
        image: ghcr.io/arm64-compat/confluentinc/cp-schema-registry
        ports:
            - "8081:8081"
        depends_on:
            - zookeeper
            - kafka
          environment:
              SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
              SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
              SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
              SCHEMA_REGISTRY_HOST_NAME: schema-registry
              SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
              SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
              SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
    control-center:
        image: ghcr.io/arm64-compat/confluentinc/cp-enterprise-control-center
        depends_on:
            - kafka
            - schema-registry
          ports:
              - "9021:9021"
          environment:
              CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
              CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
              CONTROL_CENTER_REPLICATION_FACTOR: 1
              CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
              CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
              CONFLUENT_METRICS_TOPIC_REPLICATION: 1
              PORT: 9021
